products.go
shop.go

* feat: adding products repository
* feat: products query
* docs: improve comment
Co-authored-by: Harry Withers <harry@mohc.net>

Products repository

---

.githooks/pre-commit
.githooks/pre-push
line-items.go
money.go
shipping.go
tax.go

* feat: add money
* fix: use bash
* docs: add descriptions of new structs

feat: add costs to orders (#20)

---

product-errors.go

* feat: get product
* fix: product error

Product not found

---

.githooks/pre-commit
.githooks/pre-push
collections-constants.go
collections.go
images.go
product-images.go
products.go
shop.go

Small fix for git hooks as well

Collections and product images

---

collections.go
custom-collections.go
rules-constants.go
rules.go
smart-collections.go
variants.go

- add rules to collections
- add ProductID to variant
- add smart collections
- add custom collections
- change collections to interface

feat: add rules

---

collections-constants.go
collections.go
custom-collections.go
rules-constants.go
rules.go
smart-collections.go
variants.go

* feat: add rules to collection and add productID to variant
* fix: sort rules comment
* fix: remove json from rules
* fix: add rule constants for relations
* fix: add rule constants for relations
* fix: add more info to condition param in rule
* fix: sort comments and add columns const in rule-constants file
* fix: sort comments and add columns const in rule-constants file
* feat: add productCount
* fix: add productCount in correct location
* feat: add smart collections and custom collections and change collections to a interface
* feat: add smart collections and custom collections and change collections to a interface
* feat: add smart collections and custom collections and change collections to a interface
* fix: remove rules from custom collections
* feat: add contructors for smart …

feat: collection rules (#41)

---

orders.go
products.go
tags.go

feat!: add tags to orders (#47)

---

go.mod
go.sum
metafields.go
metafields_test.go
shop.go

* feat: adding metafields models and interfaces
* refactor: tidy up unneeded variables
* refactor: metafield is one word here
* ci: injecting some testing packages
* refactor: changing the getByKey method
* test: adding tests for GetByKey
* ci: refactor go sum file
* ci: refactor go mod
* ci: lets try this version
* refactor: old style testing because of go version
* refactor: tidy mod file
* docs: adding comment to explain the default to string
* refactor: removing complexity of extra type
* docs: updating test comments
* refactor: removing unused error

feat: adding metafields models and interfaces (#73)

---

customer-errors.go
customers.go

* fix: this is not being used
* feat: adding interface for repo and phone number
* feat: adding get customer to repo interface
* feat: added customer not found error
* feat: added tags field to customer
* refactor: change Tags type to Tags
Co-authored-by: Ianmohc <ian@mohc.net>

feat: adding get customer to repo interface (#79)

---

tags.go

Added a function to get the value of a tag by its key and the separator provided.

feature: get tag value

---

tags.go

feat: added function to get a tag's value by key

---

metafields.go
metafields_test.go
orders.go
tags.go

- Allowing the update of an order
- Creating meta fields on an order
- Updating meta fields on an order
- The ability to open an order

New Features

---

customers.go

Added the customer address repo interface with a Delete function.

feat: customer address repo

---

customers.go

Added customer addresses to the customer resource

feat: customer addresses (#100)

---

customer-addresses.go
customers.go

Created a new and more suitable `CustomerAddresses` struct with a helper function to retrieve an address from the list given an ID

feat: Customer Addresses struct and helper

---

customer-addresses.go

Adds ability to set a default address for a customer

feat: set customer default address

---

orders.go

Updated the query property to allow limits.

feat: adjust results limit

---

products.go

Adding `metafields` in `Product` definition

feat: product metafield

---

shop.go
webhooks.go

Addition of the Webhook resource

feat: webhook repo

---

.github/workflows/test.yml
go.mod
metafields.go
products.go
variants.go

- Updating go version
- Int conversion fix
- Including metafields against `variant` struct

feat(SHP-2062): variant metafields and number conversion
